### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by felipemfp** [Projeto-SIAC/api#2]
:open_umbrella: __What is needed for the first release?__

- [x] Ability to see information about the authenticated user (#3)
- [x] Ability to list questions from an authenticated teacher (#4)
- [ ] Ability to create questions (with[out] options and/or with[out] attachments)
- [ ] Ability to generate assessment tests based on a list of topics or subjects, level (previously called difficulty) and quantities (subjective and objectives)
- [ ] Ability to save answers to an assessment test
- [x] Ability to check if a questions is subjective or not (without manually checking options) (#5)
- [x] Ability to check if a user is a teacher or not (without manually checking subjects) (#6)

**Comment by felipemfp** [comment]
@chicobentojr, feel free to open a issue for each one
